services:
  backend:
    restart: always
    container_name: girangir-back
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3010:3000"
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
      # Docker Compose ֆայլի volumes-ը ապահովում է, որ լոկալ ֆայլերը անմիջապես կապված լինեն Docker կոնտեյների հետ։ 
    volumes:
      - ./backend:/app # Սա կապում է լոկալ backend ֆոլդերը Docker կոնտեյների հետ
      - /app/node_modules

  frontend:
    restart: always
    container_name: girangir-front
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:8080"
    # env_file:
    #   - ./frontend/.env
    volumes:
      - ./frontend:/app

  db:
    image: postgres:13
    container_name: girangir-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
